imports:
    - { resource: config.yml }

parameters:
    database_dsn: sqlite::memory:

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: true }

web_profiler:
    toolbar: false
    intercept_redirects: false
