propel:
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    logging:    %kernel.debug%
    build_properties:
        propel.mysql.tableType:       InnoDB
        propel.builder.pluralizer.class: builder.util.StandardEnglishPluralizer

    dbal:
        default_connection:       default
        connections:
           default:
               driver:               %database_driver%
               user:                 %database_user%
               password:             %database_password%
               dsn:                  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
               options:
                   ATTR_PERSISTENT: true
               settings:
                   charset:        { value: UTF8 }
