login:
    pattern:   /login
    defaults:  { _controller: AcmeBlogBundle:Welcome:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

library:
    resource: '@AcmeLibraryBundle/Resources/config/routing.yml'
    prefix: /library
