security:
    encoders:
        Acme\BlogBundle\Security\UserProxy:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000

    role_hierarchy:
        ROLE_AUTHOR:      ROLE_USER
        ROLE_MODERATOR:   ROLE_USER
        ROLE_ADMIN:       [ ROLE_AUTHOR, ROLE_MODERATOR ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        propel:
            id: acme.security.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                username_parameter: 'login[username]'
                password_parameter: 'login[password]'
                csrf_parameter:     'login[_token]'
                csrf_provider:      form.csrf_provider

                use_referer:  true
                default_target_path: /

            remember_me:
                key: 'DJc48ht2bTKPVVXxtQbxd35WNq6'
                remember_me_parameter: 'login[remember_me]'

            logout:
                path: /logout
                target: /

            anonymous:    true
            switch_user:  false

    access_control:
        -
            path: ^/login$
            role: 'IS_AUTHENTICATED_ANONYMOUSLY'
        -
            path: ^/login_check$
            role: 'IS_AUTHENTICATED_ANONYMOUSLY'
        -
            path: ^/logout
            role: 'IS_AUTHENTICATED_ANONYMOUSLY'
